name: libratrack_client
description: "Cliente de Flutter para LibraTrack."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.5.0-15.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  nested: ^1.0.0
  
  flutter_localizations:
    sdk: flutter
  
  # --- Â¡PAQUETE AÃ‘ADIDO (ID: QA-091)! ---
  google_sign_in: ^7.2.0
  # ---

  intl: 0.20.2
  http: ^1.5.0
  flutter_secure_storage: ^9.2.4
  cached_network_image: ^3.3.1
  marquee: ^2.2.3
  image_picker: ^1.1.2
  path: ^1.9.0
  http_parser: ^4.1.2
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true 
  uses-material-design: true