name: libratrack_client
description: "Cliente de Flutter para la plataforma LibraTrack."
publish_to: 'none' # Evita publicación accidental en pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.5.0-15.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # --- Internacionalización ---
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2 # Formateo de fechas y números

  # --- Autenticación y Google ---
  google_sign_in: ^7.2.0 # Versión estable y compatible

  # --- Red y Almacenamiento ---
  http: ^1.5.0
  http_parser: ^4.1.2
  flutter_secure_storage: ^9.2.4 # Almacenamiento seguro de tokens
  shared_preferences: ^2.2.3 # Almacenamiento simple (configuración)

  # --- Gestión de Estado e Inyección ---
  provider: ^6.1.2

  # --- UI y Widgets ---
  cached_network_image: ^3.3.1 # Caché de imágenes
  flutter_svg: ^2.2.3 # Soporte SVG
  cupertino_icons: ^1.0.6
  marquee: ^2.2.3 # Texto deslizante

  # --- Utilidades ---
  image_picker: ^1.1.2 # Selección de imágenes
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # --- Linter y Generadores ---
  flutter_lints: ^6.0.0

# Configuración específica de Flutter
flutter:
  uses-material-design: true
  
  # Generación automática de código para l10n (Intl)
  generate: true 

  # Recursos estáticos
  assets:
    - assets/images/google_logo.svg
    - assets/images/isotipo_libratrack.svg

flutter_intl:
  enabled: true